name: todice
version: 1.0.0+1
publish_to: none
description: Simple To Do List App.
environment:
  sdk: ">=3.4.4 <4.0.0"

dependencies:
  cupertino_icons: ^1.0.6
  get: 4.6.6
  hive: 2.2.3
  flutter_slidable: 3.1.0
  hive_flutter: 1.1.0
  google_fonts: 6.2.1
  intl: 0.19.0
  gap: 3.0.1
  package_info_plus: 8.0.1
  flutter_local_notifications: 17.2.2
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: 4.0.0
  hive_generator: any
  build_runner: any
  flutter_launcher_icons: "^0.13.1"
  flutter_test:
    sdk: flutter

flutter_launcher_icons:
  android: "launcher_icon"
  image_path: "assets/logo-img.png"
  min_sdk_android: 21 # android min sdk min:16, default 21

flutter:
  assets:
    - assets/
  uses-material-design: true
