name: to_dice
version: 1.0.0+1
publish_to: none
description: Simple To Do List App.
environment: 
  sdk: '>=3.4.4 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.6
  get: 4.6.6
  hive: 2.2.3
  flutter_slidable: 3.1.0
  hive_flutter: 1.1.0
  google_fonts: 6.2.1
  intl: 0.19.0
  gap: 3.0.1
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: 4.0.0
  hive_generator: any
  build_runner: any
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true
  assets:
    - assets/


